name: CI
run-name: Build main - ${{ github.actor }} ğŸš€
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allow manual triggering

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Ensure previous builds don't affect this build
      - name: ğŸ§¼ Cleanup
        run: rm -rf build/

      - name: ğŸ§¾ Checkout source code
        uses: actions/checkout@v4

      - name: â˜• Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ”‘ Grant permissions
        run: chmod +x ./gradlew

      - name: ğŸ§ª+ ğŸ› ï¸ Test and build app
        run: ./gradlew clean build --console=auto -Dorg.gradle.logging.level=LIFECYCLE

#      - name: ğŸ³ Build Docker Image
#        run: docker build -t country-api:${{ github.sha }} .